---
- name: Add the armhf architecture
  shell: dpkg --add-architecture armhf
  become: true


- name: Install the packages required for OpenCR update
  apt:
    state: present
    update_cache: yes
    pkg: libc6:armhf

- name: Unarchive the openCR firmware
  unarchive:
    src: https://github.com/ROBOTIS-GIT/OpenCR-Binaries/raw/master/turtlebot3/ROS2/latest/opencr_update.tar.bz2
    dest: /opt/
    remote_src: yes
  register: opencr

- name: Firmware update
  shell: |
    cd /opt/opencr_update
    ./update.sh /dev/ttyACM0 {{ turtlebot3_model }}.opencr
  become: true
  when: opencr.changed
