network:
  version: 2
  rendererer: networkd
  ethernets:
    eth0: 
      dhcp4: yes
      dhcp6: yes
      optional: true
  wifis:
    wlan0:
      dhcp4: yes
      dhcp6: yes
      access-points:
        {{ robot_wifi_ssid }}:
          password: {{ robot_wifi_password }}

