network:
  version: 2
  rendererer: networkd
  ethernets:
    enp3s0f2: 
      dhcp4: yes
      dhcp6: yes
      optional: true
  wifis:
    wlp2s0:
      dhcp4: yes
      dhcp6: yes
      access-points:
        {{ robot_wifi_ssid }}:
          password: {{ robot_wifi_password }}

