
- name: Disabling the auto updates with apt
  copy:
    src: files/etc/apt/apt.conf.d/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: Update and upgrade apt packages, can be long
  become: true
  apt:
    upgrade: yes
    update_cache: yes

# setfacl is required for a later task (in turtlebot3 role) with become_user
- name: Installation of acl (for setfacl)
  apt: pkg=acl state=present update_cache=true
